[project]
name = "JAMEd"
dynamic = ["version"]
dependencies = [
    "pathlib",
    "pandas",
    "packaging",
    "pint"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = {attr = "JAMEd.version.__version__"}